import { Analytics } from '@vercel/analytics/react';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ActiveLink } from '@/ui/atoms/ActiveLink';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <ul>
            <li>
              <ActiveLink href="/">Home</ActiveLink>
            </li>
            <li>
              <ActiveLink href="/products">All</ActiveLink>
            </li>
          </ul>
        </nav>
        <section className="mx-auto max-w-md p-12 sm:max-w-2xl sm:py-16 md:max-w-4xl lg:max-w-7xl">
          {children}
        </section>
        <footer>
          <p className="text-center text-sm text-gray-500">@2023</p>
        </footer>
      </body>
      <Analytics />
    </html>
  );
}
